services:
  proxy:
    image: nginx:1.29
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ukdwseru

  wordpress:
    image: wordpress:6.8.2
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASS}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
    volumes:
      - wordpress:/var/www/html
    networks:
      - ukdwseru

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ukdwseru

  pma:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./apache.conf:/etc/apache2/conf-enabled/apache.conf:ro
    environment:
      PMA_HOST: mysql
    networks:
      - ukdwseru

volumes:
  wordpress:
  db_data:

networks:
  ukdwseru:
